### ISSUE TITLE
protect against minus numbers in input

### ISSUE THREAD

**Issue by jcb121** [seedcode/SpirographN#1]
protect against minus numbers in input for the rotor. awesome program 👍 

`Uncaught DOMException: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-1) is negative.
    at drawOneCircle (http://seedcode.com/SpirographN/sgn.js:1093:7)
    at drawCircles (http://seedcode.com/SpirographN/sgn.js:1038:5)
    at draw (http://seedcode.com/SpirographN/sgn.js:1218:4)`

**Comment by JasonChrYoung** [comment]
Thank You! Corrected in latest commit.
